version: "3"
services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "8080:80"
  primary:
    build:
      context: .
    ports:
      - "8081:3000"
    privileged: true
    environment:
      FLY_REGION: primary
      IS_PRIMARY: "true"
  replica1:
    build:
      context: .
    ports:
      - "8082:3000"
    privileged: true
    environment:
      FLY_REGION: replica1
      IS_PRIMARY: "false"
